version: "3.7"

networks:
  covid:
    name: covid_network

services:
  app:
    image: app_covid
    networks: 
      - covid
    build:
      context: ./Maven
    ports:
      - "80:8080"
    depends_on: 
      - postgres
  postgres:
    image: postgres_covid
    networks: 
      - covid
    build:
      context: ./PostgreSQL
    ports:
      - "5432:5432"