
/*
 * Create the database
 */
CREATE DATABASE COVIDITALY;

/*
 * Select the Schema
 */
\c coviditaly;

/*
 * Table that contains the list of natial data
 */
CREATE TABLE NATIONAL_DATA (
	DATE_DATA				DATE							NOT NULL PRIMARY KEY,
	NEW_INFECTIONS			INTEGER 			DEFAULT 0	NOT NULL,
	NEW_TESTS				INTEGER				DEFAULT 0	NOT NULL,
	NEW_CASUALTIES			INTEGER				DEFAULT 0	NOT NULL,
	NEW_HOSPITALIZED		INTEGER				DEFAULT 0	NOT NULL,
	NEW_INTENSIVE_THERAPY	INTEGER				DEFAULT 0	NOT NULL,
	NEW_RECOVERED			INTEGER				DEFAULT 0	NOT NULL,
	INFECTION_PERC			DECIMAL( 7, 2)		DEFAULT 0	NOT NULL,
	CASUALTIES_PERC			DECIMAL( 7, 2)		DEFAULT 0	NOT NULL
);

CREATE TABLE REGIONAL_DATA (
	DATE_DATA				DATE							NOT NULL,
	REGION_CODE				VARCHAR(3)			DEFAULT ''	NOT NULL,
	NEW_INFECTIONS			INTEGER 			DEFAULT 0	NOT NULL,
	NEW_TESTS				INTEGER				DEFAULT 0	NOT NULL,
	NEW_CASUALTIES			INTEGER				DEFAULT 0	NOT NULL,
	NEW_HOSPITALIZED		INTEGER				DEFAULT 0	NOT NULL,
	NEW_INTENSIVE_THERAPY	INTEGER				DEFAULT 0	NOT NULL,
	NEW_RECOVERED			INTEGER				DEFAULT 0	NOT NULL,
	INFECTION_PERC			DECIMAL( 7, 2)		DEFAULT 0	NOT NULL,
	CASUALTIES_PERC			DECIMAL( 7, 2)		DEFAULT 0	NOT NULL,
	PRIMARY KEY (DATE_DATA, REGION_CODE)
);

CREATE TABLE PROVINCE_DATA (
	DATE_DATA				DATE							NOT NULL,
	REGION_CODE				VARCHAR(3)			DEFAULT ''	NOT NULL,
	PROVINCE_CODE			VARCHAR(3)			DEFAULT ''	NOT NULL,
	REGION_DESC				VARCHAR(100)		DEFAULT ''	NOT NULL,
	DESCRIPTION				VARCHAR(100)		DEFAULT ''	NOT NULL,
	PROVINCE_SHORT			VARCHAR(2)			DEFAULT ''	NOT NULL,
	NEW_INFECTIONS			INTEGER 			DEFAULT 0	NOT NULL,
	PRIMARY KEY(DATE_DATA, REGION_CODE, PROVINCE_CODE)
);
