logging:
  level:
    root: INFO
    com: 
      marco:
        javacovidstatus: DEBUG

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/coviditaly
    username: postgres
    password: postgres


server:  servlet:    context-path: /Covid19Italy