logging:
  file:    name: ./logs/covid-status.log
  pattern:
    console: "%d %-5level : %msg%n"
    file: "%d %-5level : %msg%n"
  level:
    root: INFO
    com:
      marco:
        javacovidstatus: DEBUG

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/coviditaly
    username: postgres
    password: postgres
  #autoconfigure:
    #exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration, org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
  mail:    host: smtp.gmail.com
    port: 587
    username: XXXX
    password: XXXX
    properties:      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:  servlet:    context-path: /Covid19Italy
    
covidstatus:
  notification:
    enabled: false
  scheduled:
    downloadnewdata:
      cron: "0 0 * * * *" # Every hour